JambudeskRecordBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JambudeskRecordBundle:Default:index }

JambudeskRecordBundle_form:
    pattern:  /form/{slug}
    defaults: { _controller: JambudeskRecordBundle:Form:index }

JambudeskRecordBundle_record_save:
    pattern:  /record/save
    defaults: { _controller: JambudeskRecordBundle:Record:save }