parameters:
#    jambudesk_record.example.class: Jambudesk\RecordBundle\Example

services:
#    jambudesk_record.example:
#        class: %jambudesk_record.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
